### ISSUE TITLE
Make the home page responsive

### ISSUE THREAD

**Issue by hassanuahmad** [Windsor-Code-Camp/wcc-frontend#15]

**Comment by JagrajAulakh** [comment]
HeroSection has "mobile" and "desktop" versions:
## Desktop

![image](https://user-images.githubusercontent.com/22580729/152707195-0f741492-8e78-4c89-b2c0-f7bfd84bc045.png)

## Mobile

![image](https://user-images.githubusercontent.com/22580729/152707232-ba360678-bbc2-4736-ab49-2df6d2038c00.png)

**Comment by JagrajAulakh** [comment]
HeroSection has a "mobile" and "desktop" version

## Desktop

- Left-aligned text
- Content is side-to-side

![image](https://user-images.githubusercontent.com/22580729/152713139-bdb2e4b3-b494-46ad-b921-947ac66804b7.png)

## Mobile

- Center-aligned text
- Smaller font sizes
- Content is stacked

![image](https://user-images.githubusercontent.com/22580729/152713160-6d87648d-6b75-40e9-af85-98261ff7b6f3.png)

**Comment by JagrajAulakh** [comment]
WhyWCC section:

## Desktop

![image](https://user-images.githubusercontent.com/22580729/152906290-76f6bebb-d5b6-4ef6-a104-22e5cce53e01.png)
![image](https://user-images.githubusercontent.com/22580729/152905828-0c550a8a-1578-48e5-9e2c-6b0e52a962af.png)


## Mobile

![image](https://user-images.githubusercontent.com/22580729/152905885-f86544f3-319a-4f05-b8b4-5da202be2d0e.png)
![image](https://user-images.githubusercontent.com/22580729/152905922-cbcfe14c-c7aa-4434-8f6c-15880c2cf3c0.png)

**Comment by JagrajAulakh** [comment]
For Carousel breakpoints:
https://sag1v.github.io/react-elastic-carousel/breakPoints

**Comment by JagrajAulakh** [comment]
## WhatOurStudentsSay section is responsive:

Showing different number of cards based on tailwind breakpoints:

![image](https://user-images.githubusercontent.com/22580729/153283573-4da5166f-41ca-4d85-bcfc-19e553d4a6a9.png)

![image](https://user-images.githubusercontent.com/22580729/153283621-d9ce2751-00df-4ba5-8339-72523761a0c4.png)

![image](https://user-images.githubusercontent.com/22580729/153283653-269019a8-ca57-4901-9d7e-0701852c25aa.png)

**Comment by JagrajAulakh** [comment]
OurCoursesSection is now responsive

## Desktop

![image](https://user-images.githubusercontent.com/22580729/153297881-23291946-516f-4d67-89c4-cc6ecbc9206d.png)

## Mobile

![image](https://user-images.githubusercontent.com/22580729/153297968-f81e6cfb-4b01-4a03-af38-6dd87be72055.png)

**Comment by JagrajAulakh** [comment]
Footer is now responsive

## Desktop

![image](https://user-images.githubusercontent.com/22580729/153298082-0bd2dfa1-0dd2-49b3-bc24-a7c09bd45396.png)

## Mobile

![image](https://user-images.githubusercontent.com/22580729/153298115-c9426270-1749-4642-b9d6-cc507388202f.png)

**Comment by hassanuahmad** [comment]
**FIX** WHY WCC section padding on mobile

**Comment by hassanuahmad** [comment]
**FIX** OUR COURSES text looks bad on mobile because of the br tag

**Comment by hassanuahmad** [comment]
**FIX** JOIN OUR COMMUNITY text on mobile because of br tag

**Comment by hassanuahmad** [comment]
Add flex-col to the JOIN US in footer

**Comment by JagrajAulakh** [comment]
FIX OUR COURSES text looks bad on mobile because of the br tag
br tag
flex-col to the JOIN US in footer

**Comment by JagrajAulakh** [comment]
This is a stupidly large issue. We should've split it up into sections.

*For next time I guess.............*
